[package]
name = "rs06"
version = "0.1.0"
authors = ["laiso <laiso@lai.so>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
